// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EMarketDataType.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "EMarketDataType.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace htsc {
namespace mdc {
namespace insight {
namespace model {

namespace {

const ::google::protobuf::EnumDescriptor* EMarketDataType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_EMarketDataType_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_EMarketDataType_2eproto() {
  protobuf_AddDesc_EMarketDataType_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "EMarketDataType.proto");
  GOOGLE_CHECK(file != NULL);
  EMarketDataType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_EMarketDataType_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_EMarketDataType_2eproto() {
}

void protobuf_InitDefaults_EMarketDataType_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_EMarketDataType_2eproto_once_);
void protobuf_InitDefaults_EMarketDataType_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_EMarketDataType_2eproto_once_,
                 &protobuf_InitDefaults_EMarketDataType_2eproto_impl);
}
void protobuf_AddDesc_EMarketDataType_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_EMarketDataType_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025EMarketDataType.proto\022\032com.htsc.mdc.in"
    "sight.model*\264\005\n\017EMarketDataType\022\025\n\021UNKNO"
    "WN_DATA_TYPE\020\000\022\013\n\007MD_TICK\020\001\022\022\n\016MD_TRANSA"
    "CTION\020\002\022\014\n\010MD_ORDER\020\003\022\017\n\013MD_CONSTANT\020\004\022\022"
    "\n\016DYNAMIC_PACKET\020\005\022\024\n\020MD_ETF_BASICINFO\020\006"
    "\022\021\n\rMD_KLINE_1MIN\020\024\022\021\n\rMD_KLINE_5MIN\020\025\022\022"
    "\n\016MD_KLINE_15MIN\020\026\022\022\n\016MD_KLINE_30MIN\020\027\022\022"
    "\n\016MD_KLINE_60MIN\020\030\022\017\n\013MD_KLINE_1D\020\031\022\020\n\014M"
    "D_KLINE_15S\020\032\022\020\n\014MD_TWAP_1MIN\020\036\022\016\n\nMD_TW"
    "AP_1S\020\037\022\020\n\014MD_VWAP_1MIN\020(\022\016\n\nMD_VWAP_1S\020"
    ")\022\022\n\016MD_SIMPLE_TICK\0202\022\030\n\024AD_UPSDOWNS_ANA"
    "LYSIS\0203\022\031\n\025AD_INDICATORS_RANKING\0204\022\025\n\021AD"
    "_VOLUME_BYPRICE\0205\022\031\n\025AD_FUND_FLOW_ANALYS"
    "IS\0206\022\031\n\025AD_ORDERBOOK_SNAPSHOT\0207\022#\n\037AD_OR"
    "DERBOOK_SNAPSHOT_WITH_TICK\0208\022\030\n\024AD_CHIP_"
    "DISTRIBUTION\0209\022\017\n\013MD_FI_QUOTE\020F\022#\n\037REPLA"
    "Y_MD_TICK_WITH_TRANSACTION\020e\022\035\n\031REPLAY_M"
    "D_TICK_WITH_ORDER\020f\022-\n)REPLAY_MD_TICK_WI"
    "TH_TRANSACTION_AND_ORDER\020gB7\n\032com.htsc.m"
    "dc.insight.modelB\024EMarketDataTypeProtoH\001"
    "\240\001\001b\006proto3", 811);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "EMarketDataType.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_EMarketDataType_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_EMarketDataType_2eproto_once_);
void protobuf_AddDesc_EMarketDataType_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_EMarketDataType_2eproto_once_,
                 &protobuf_AddDesc_EMarketDataType_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_EMarketDataType_2eproto {
  StaticDescriptorInitializer_EMarketDataType_2eproto() {
    protobuf_AddDesc_EMarketDataType_2eproto();
  }
} static_descriptor_initializer_EMarketDataType_2eproto_;
const ::google::protobuf::EnumDescriptor* EMarketDataType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EMarketDataType_descriptor_;
}
bool EMarketDataType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 30:
    case 31:
    case 40:
    case 41:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 70:
    case 101:
    case 102:
    case 103:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace model
}  // namespace insight
}  // namespace mdc
}  // namespace htsc
}  // namespace com

// @@protoc_insertion_point(global_scope)
